# Generated by Django 5.2.1 on 2025-05-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_carteira', models.CharField(max_length=50)),
                ('validade_carteira', models.DateField()),
                ('atendimento_rn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operadora', models.CharField(max_length=50)),
                ('nome_contratado', models.CharField(max_length=255)),
                ('cnes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=50)),
                ('codigo_procedimento', models.CharField(max_length=50)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=255)),
                ('conselho_profissional', models.CharField(max_length=100)),
                ('numero_conselho_profissional', models.CharField(max_length=50)),
                ('uf_profissional', models.CharField(max_length=2)),
                ('cbo_profissional', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoRealizado',
            fields=[
                ('procedimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tiss_api.procedimento')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('via_acesso', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('tiss_api.procedimento',),
        ),
        migrations.CreateModel(
            name='ProcedimentosSolicitados',
            fields=[
                ('procedimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tiss_api.procedimento')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade_solicitado', models.PositiveIntegerField()),
            ],
            bases=('tiss_api.procedimento',),
        ),
        migrations.CreateModel(
            name='GuiaSPSADT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=20)),
                ('numero_guia', models.CharField(max_length=20, unique=True)),
                ('tipo_guia', models.CharField(max_length=50)),
                ('numero_guia_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('data_autorizacao', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
                ('validade_senha', models.DateField(blank=True, null=True)),
                ('codigo_operadora_solic', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_contratado_solic', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_profissional_solic', models.CharField(blank=True, max_length=100, null=True)),
                ('conselho_profissional_solic', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_conselho_solic', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_profissional_solic', models.CharField(blank=True, max_length=2, null=True)),
                ('cbo_profissional_solic', models.CharField(blank=True, max_length=10, null=True)),
                ('assinatura_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('indicacao_clinica', models.TextField(blank=True, null=True)),
                ('indicador_cobertura_especial', models.CharField(blank=True, max_length=50, null=True)),
                ('items_solicitados', models.TextField(blank=True, null=True)),
                ('tipo_atendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('indicacao_acidente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_consulta', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_encerramento', models.CharField(blank=True, max_length=100, null=True)),
                ('regime_atendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('saude_ocupacional', models.BooleanField(default=False)),
                ('cpf_executor', models.CharField(blank=True, max_length=11, null=True)),
                ('nome_profissional_exec', models.CharField(blank=True, max_length=100, null=True)),
                ('conselho_profissional_exec', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_conselho_exec', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_profissional_exec', models.CharField(blank=True, max_length=2, null=True)),
                ('cbo_profissional_exec', models.CharField(blank=True, max_length=10, null=True)),
                ('observacao_justificativa', models.TextField(blank=True, null=True)),
                ('total_procedimentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_taxes_alugueis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_materiais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_opme', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_medicamentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gases_medicinais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.beneficiario')),
                ('contratado_executante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guias_spsadt', to='tiss_api.contratado')),
                ('procedimentos_realizados', models.ManyToManyField(blank=True, related_name='guias_spsadt_procedimentos', to='tiss_api.procedimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=20)),
                ('numero_guia', models.CharField(max_length=20, unique=True)),
                ('tipo_guia', models.CharField(max_length=50)),
                ('numero_guia_prestador', models.CharField(max_length=20)),
                ('indicacao_acidente', models.CharField(blank=True, max_length=50, null=True)),
                ('indicador_cobertura_especial', models.CharField(blank=True, max_length=50, null=True)),
                ('regime_atendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('saude_ocupacional', models.BooleanField(default=False)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.beneficiario')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.contratado')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.procedimento')),
                ('profissional_executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.profissional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
