# Generated by Django 5.2.1 on 2025-06-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carteira', models.CharField(max_length=20)),
                ('validade_carteira', models.DateField(blank=True, null=True)),
                ('atendimento_rn', models.BooleanField()),
                ('nome', models.CharField(max_length=70)),
                ('nome_social', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operadora', models.CharField(max_length=14)),
                ('nome_contratado', models.CharField(max_length=70)),
                ('cnes', models.CharField(default='9999999', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(choices=[('00', 'Tabela Própria da operadora'), ('01', 'Terminologia Unificada da Saúde Suplementar – TUSS – Procedimentos e Eventos em Saúde'), ('02', 'Terminologia Unificada da Saúde Suplementar – TUSS – Materiais'), ('03', 'Terminologia Unificada da Saúde Suplementar – TUSS – Medicamentos'), ('20', 'Tabela de Procedimentos, Medicamentos e OPM do SUS'), ('22', 'TUSS'), ('98', 'Tabela Não Contemplada pela TISS')], max_length=2)),
                ('codigo_procedimento', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=70)),
                ('conselho_profissional', models.CharField(choices=[('01', 'Conselho Regional de Medicina'), ('02', 'Conselho Regional de Odontologia'), ('06', 'Conselho Regional de Psicologia')], max_length=2)),
                ('numero_conselho', models.CharField(max_length=15)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('codigo_cbo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=6)),
                ('numero_guia_prestador', models.CharField(max_length=20)),
                ('numero_guia_operadora', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Cancelada'), ('3', 'Substituída'), ('4', 'Glosada'), ('5', 'liquidada')], default='', max_length=20)),
                ('indicacao_acidente', models.CharField(choices=[('0', 'Não'), ('1', 'Sim - Acidente Relacionado ao Trabalho'), ('2', 'Sim - Outros Tipos de Acidente')], max_length=1)),
                ('indicador_cobertura_especial', models.CharField(blank=True, choices=[('PG', 'Gestante'), ('PN', 'Pré-Natal'), ('PP', 'Pós-Parto'), ('CP', 'Cobertura Parcial Temporária (CPT)')], max_length=2, null=True)),
                ('regime_atendimento', models.CharField(blank=True, choices=[('01', 'Ambulatorial'), ('02', 'Hospital Dia'), ('03', 'Internação Hospitalar'), ('04', 'Atendimento Domiciliar'), ('05', 'Urgência/Emergência')], max_length=2, null=True)),
                ('saude_ocupacional', models.BooleanField(default=False)),
                ('data_atendimento', models.DateField(null=True)),
                ('tipo_consulta', models.CharField(choices=[('1', 'Primeira consulta'), ('2', 'Consulta de revisão'), ('3', 'Atendimento de urgência')], max_length=1)),
                ('tabela', models.CharField(choices=[('00', 'Tabela Própria da Operadora ou Outras Terminologias'), ('01', 'TUSS - Procedimentos e Eventos em Saúde'), ('02', 'TUSS - Materiais'), ('03', 'TUSS - Medicamentos'), ('20', 'Tabela de Procedimentos, Medicamentos e OPM do SUS'), ('98', 'Terminologia Não Contemplada pela TISS')], max_length=2)),
                ('codigo_procedimento', models.CharField(max_length=10)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.beneficiario')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.contratado')),
                ('profissional_executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.profissional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
