# Generated by Django 5.2.1 on 2025-05-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('nome_social', models.CharField(blank=True, max_length=70, null=True)),
                ('numero_carteira', models.CharField(max_length=20)),
                ('validade_carteira', models.DateField(blank=True, null=True)),
                ('atendimento_rn', models.BooleanField()),
                ('indicacao_acidente', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operadora', models.CharField(max_length=14)),
                ('nome_contratado', models.CharField(max_length=70)),
                ('cnes', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaSPSADT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=6)),
                ('numero_guia_prestador', models.CharField(max_length=20, unique=True)),
                ('numero_guia_operadora', models.CharField(blank=True, max_length=20, null=True)),
                ('data_autorizacao', models.DateField(blank=True, null=True)),
                ('senha_autorizacao', models.CharField(blank=True, max_length=20, null=True)),
                ('profissional_solicitante', models.CharField(max_length=70)),
                ('conselho_solicitante', models.CharField(max_length=2)),
                ('numero_conselho_solicitante', models.CharField(max_length=15)),
                ('uf_solicitante', models.CharField(max_length=2)),
                ('cbo_solicitante', models.CharField(max_length=6)),
                ('tipo_atendimento', models.CharField(max_length=2)),
                ('indicacao_clinica', models.TextField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(blank=True, max_length=1, null=True)),
                ('motivo_encerramento', models.CharField(blank=True, max_length=2, null=True)),
                ('total_geral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.paciente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.prestador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=6)),
                ('numero_guia_prestador', models.CharField(max_length=20, unique=True)),
                ('numero_guia_operadora', models.CharField(blank=True, max_length=20, null=True)),
                ('data_autorizacao', models.DateField(blank=True, null=True)),
                ('senha_autorizacao', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_profissional', models.CharField(max_length=70)),
                ('conselho', models.CharField(max_length=2)),
                ('numero_conselho', models.CharField(max_length=15)),
                ('uf', models.CharField(max_length=2)),
                ('cbo', models.CharField(max_length=6)),
                ('data_atendimento', models.DateField()),
                ('tipo_consulta', models.CharField(max_length=1)),
                ('tabela', models.CharField(max_length=2)),
                ('codigo_procedimento', models.CharField(max_length=10)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.paciente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiss_api.prestador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('tabela', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=150)),
                ('quantidade', models.IntegerField()),
                ('via_acesso', models.CharField(blank=True, max_length=1, null=True)),
                ('tecnica', models.CharField(blank=True, max_length=1, null=True)),
                ('fator_reducao', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('guia_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_consulta', to='tiss_api.guiaconsulta')),
                ('guia_spsadt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_spsadt', to='tiss_api.guiaspsadt')),
            ],
        ),
        migrations.AddField(
            model_name='guiaspsadt',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='guias_spsadt', to='tiss_api.procedimento'),
        ),
    ]
